_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

login:
    pattern:   /login
    defaults:  { _controller: SecurityProfileBundle:Security:login }
    
login_check:
    pattern:   /login_check
    
tests:
    pattern: /tests
    defaults: {_controller: TestPollBundle:TestController:show }

logout:
    path:     /logout