<?php

namespace Test\PollBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function getQuestionsForTest($testId, $approved = true)
    {
        $qb = $this->createQueryBuilder('q')
                   ->select('q')
                   ->where('q.test = :test_id')
                   ->addOrderBy('q.id')
                   ->setParameter('test_id', $testId);

        if (false === is_null($approved))
            $qb->andWhere('q.approved = :approved')
               ->setParameter('approved', $approved);

        return $qb->getQuery()
                  ->getArrayResult();
   /*     
        for ($i=0; $i<count(  $questions ) ; $i++)
        {
            $qb = $this->createQueryBuilder('a')
                       ->select('a')
                       ->where('a.question = :question_id')
                       ->addOrderBy('a.id')
                       ->setParameter('question_id', $questions[$i]['id']);
            $question[$i]['answers'] = $qb->getQuery()
                                          ->getResult();
                       
        }
    * */
    
    }
}
