<?php

namespace Test\PollBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
   public function getTests($limit = null)
    {
        $qb = $this->createQueryBuilder('t')
                   ->select('t')
                   ->addOrderBy('t.title', 'ASC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
