<?php

namespace Test\PollBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserAnswerPaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswerPaperRepository extends EntityRepository
{
}
